version: '3.1'

services:
  catalog-back:
    build: .
    ports:
      - 8001:8001
    volumes:
      - ./:/app
  
  catalog-db:
    image: postgres:13
    ports: 
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=catalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
